### ISSUE TITLE
cannot use Carnet app

### ISSUE THREAD

**Issue by heimchemiker** [CarnetApp/CarnetNextcloud#194]
I am having a problem using the carnet app within nextcloud. Whenever I open the app, I am only getting the empty carnet app screen, witht the nextcloud bar at the top, the carnet menue on the left and an emty main space with "something went wrong...please reload" ("etwas ist schiefgelaufen...Bitte neu laden").
![image](https://user-images.githubusercontent.com/46328969/184883810-2279fbb9-886e-4889-89ad-a338c4f2b017.png)

The logfile from Nextcloud says:

> [index] Fehler: OCP\Files\NotPermittedException: Could not create folder at <<closure>>
> 
> 0. /var/www/nextcloud/apps/carnet/lib/Controller/NoteController.php line 213
>    OC\Files\Node\Folder->newFolder()
> 1. /var/www/nextcloud/apps/carnet/lib/Controller/NoteController.php line 464
>    OCA\Carnet\Controller\NoteController->getRecentFile()
> 2. /var/www/nextcloud/apps/carnet/lib/Controller/NoteController.php line 135
>    OCA\Carnet\Controller\NoteController->mergeRecentDB()
> 3. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 225
>    OCA\Carnet\Controller\NoteController->getRecent()
> 4. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 133
>    OC\AppFramework\Http\Dispatcher->executeController()
> 5. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
>    OC\AppFramework\Http\Dispatcher->dispatch()
> 6. /var/www/nextcloud/lib/private/Route/Router.php line 298
>    OC\AppFramework\App::main()
> 7. /var/www/nextcloud/lib/base.php line 1023
>    OC\Route\Router->match()
> 8. /var/www/nextcloud/index.php line 36
>    OC::handleRequest()
> 
> GET /apps/carnet/recentdb
> from _IP_ by Steve at 2022-08-16T14:25:20+02:00

I am Running Nextcloud in a VM with Ubuntu 20.04.1 LTS, php8.0.22, postgresql 13.8, nextcloud 24.0.3, and carnet in version 0.24.5.

One thing I suspect as a source for the error is that I have the user data directories not directly in the Nextcloud VM, but mounted as SMB Shares:
![image](https://user-images.githubusercontent.com/46328969/184882740-e6034ba3-cc7c-4eb3-b080-74c3d3bf8355.png)
this works for all other apps and usage forms but might be the problem here. 
Each user is able to create and delete files in their mounted folder, which is why I don't understand the "could not create folder" from the error message.

If you need additional information, please ask and I'll upload them.

**Comment by demuxer86** [comment]
I am so freaking greatful this app was fixed for nextcloud 28. 

Seriously, this app needs to be the official notes app.  The nextcloud team should buy this guy out or whatever, and include this by default.   It completely destroys all other notes apps in terms of usability.   It's an essential tool for me, no less significant than nextcloud itself.

**Comment by demuxer86** [comment]
> I am having a problem using the carnet app within nextcloud. Whenever I open the app, I am only getting the empty carnet app screen, witht the nextcloud bar at the top, the carnet menue on the left and an emty main space with "something went wrong...please reload" ("etwas ist schiefgelaufen...Bitte neu laden"). ![image](https://user-images.githubusercontent.com/46328969/184883810-2279fbb9-886e-4889-89ad-a338c4f2b017.png)
> 
> The logfile from Nextcloud says:
> 
> > [index] Fehler: OCP\Files\NotPermittedException: Could not create folder at <>
> > 
> > 0. /var/www/nextcloud/apps/carnet/lib/Controller/NoteController.php line 213
> >    OC\Files\Node\Folder->newFolder()
> > 1. /var/www/nextcloud/apps/carnet/lib/Controller/NoteController.php line 464
> >    OCA\Carnet\Controller\NoteController->getRecentFile()
> > 2. /var/www/nextcloud/apps/carnet/lib/Controller/NoteController.php line 135
> >    OCA\Carnet\Controller\NoteController->mergeRecentDB()
> > 3. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 225
> >    OCA\Carnet\Controller\NoteController->getRecent()
> > 4. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 133
> >    OC\AppFramework\Http\Dispatcher->executeController()
> > 5. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
> >    OC\AppFramework\Http\Dispatcher->dispatch()
> > 6. /var/www/nextcloud/lib/private/Route/Router.php line 298
> >    OC\AppFramework\App::main()
> > 7. /var/www/nextcloud/lib/base.php line 1023
> >    OC\Route\Router->match()
> > 8. /var/www/nextcloud/index.php line 36
> >    OC::handleRequest()
> > 
> > GET /apps/carnet/recentdb
> > from _IP_ by Steve at 2022-08-16T14:25:20+02:00
> 
> I am Running Nextcloud in a VM with Ubuntu 20.04.1 LTS, php8.0.22, postgresql 13.8, nextcloud 24.0.3, and carnet in version 0.24.5.
> 
> One thing I suspect as a source for the error is that I have the user data directories not directly in the Nextcloud VM, but mounted as SMB Shares: ![image](https://user-images.githubusercontent.com/46328969/184882740-e6034ba3-cc7c-4eb3-b080-74c3d3bf8355.png) this works for all other apps and usage forms but might be the problem here. Each user is able to create and delete files in their mounted folder, which is why I don't understand the "could not create folder" from the error message.
> 
> If you need additional information, please ask and I'll upload them.

Everything you're running is far outdated.  I wouldn't bother trying to figure out why it doesnt work.  It will be easier to run updates and fix what that breaks.

**Comment by heimchemiker** [comment]
Hi @demuxer86,
I know, that the infos from my original post are outdated, the post is from August **2022**.
I have since then switched to Ubuntu 22.04, Nextcloud 28.0.3, php8.2.17, psql 13.13, and the current Carnet app is currently running. The user data directories are still SMB shares.
Since my original post the carnet app was disabled but not removed. I activated i again, still the same problem. I removed it, installed it again, still the same probelm. The logfile still says:
`NotPermittedException Could not create folder "/Steve/files/Carnet/quickdoc/recentdb"

1. /var/www/nextcloud/apps/carnet/lib/Controller/NoteController.php Zeile 216:
OC\Files\Node\Folder->newFolder()
2. /var/www/nextcloud/apps/carnet/lib/Controller/NoteController.php Zeile 467:
OCA\Carnet\Controller\NoteController->getRecentFile()
3. /var/www/nextcloud/apps/carnet/lib/Controller/NoteController.php Zeile 138:
OCA\Carnet\Controller\NoteController->mergeRecentDB()
4. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php Zeile 230:
OCA\Carnet\Controller\NoteController->getRecent()
5. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php Zeile 137:
OC\AppFramework\Http\Dispatcher->executeController()
6. /var/www/nextcloud/lib/private/AppFramework/App.php Zeile 184:
OC\AppFramework\Http\Dispatcher->dispatch()
7. /var/www/nextcloud/lib/private/Route/Router.php Zeile 315:
OC\AppFramework\App::main()
8. /var/www/nextcloud/lib/base.php Zeile 1069:
OC\Route\Router->match()
9. /var/www/nextcloud/index.php Zeile 39:
OC::handleRequest()`

**Comment by thomasfrobieter** [comment]
Not sure where to find the log, but I also get a "something went wrong...please reload". I was able to create one note and after reload I can even see it for 1-2 seconds, but I cant edit it, nor I am able to create further ones. I can see the sqd file(s) in de coducments/quicknote folder.
